services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    environment:
      QDRANT__STORAGE__PATH: /qdrant/storage
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data: